name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet/version: ['2.1', '3.1', '5']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        MERCHANT_VPOS_TOKEN: ${{ secrets.MERCHANT_VPOS_TOKEN }}
        GPO_POS_ID: ${{ secrets.GPO_POS_ID }}
        GPO_SUPERVISOR_CARD: ${{ secrets.GPO_SUPERVISOR_CARD }}
        VPOS_PAYMENT_CALLBACK_URL: ${{ secrets.VPOS_PAYMENT_CALLBACK_URL }}
        VPOS_REFUND_CALLBACK_URL: ${{ secrets.VPOS_REFUND_CALLBACK_URL }}
